### ISSUE TITLE
Ensure component consistency

### ISSUE THREAD

**Issue by KennethEnevoldsen** [HLasse/TextDescriptives#169]
It seems we are building up quite a few inconsistencies between our components. We these typically or minor they can cause confusion and duplicate code. E.g. the inconsistent naming in #168 and the inconsistencies is when something uses a getter vs. when something uses a setter (see #151).

I suggest that we do a refactor where:
- 1) All getters are in their own script. This should ensures that getters are re-used across implementations. It also allows us to document them all at once in a name page on the docs site.
- 2) Everything on a token, doc and sentence (not span just sentence-level) is set unless we specifically want it to be dynamic (e.g. the pased_quality_filter is dynamic to allow the user to change the filter after processing calculation of the metrics is a filter based on is not).
- 3) Getter is, by default, only used for spans
- 4) Set everything as an attribute to their respective docs. This will naturally increase the amount of possible extension we set on the doc level, but it will also make it much easier to just use one of attributes. We should still set the global attributes, but that can then simply be a collection of metrics that needs to be set. Essentially this could transform all components into simply being a list of attributes it should convert to a flat dictionary.

@HLasse let me know what your thoughts are on this

Edit: this would also allow refactoring the quality threshold to be agnostic to any feature.

**Comment by HLasse** [comment]
Sorry about the delay on getting back to you on this - I meant to catch you in person but a bit too late for that now ;)

I think your suggestions are spot on. The codebase has grown a lot since the early days, and your refactoring suggestions would make future development easier, and make the package more consistent and easy to maintain. 

It is a fairly extensive refactoring though. I'm fairly busy until I return to Denmark, but I can take a stab at it there. You're welcome to give it a go beforehand if you find the time but no pressure at all.
