### ISSUE TITLE
Different readability scores between textdescriptives and textstat

### ISSUE THREAD

**Issue by rnckp** [HLasse/TextDescriptives#265]
I noticed substantial differences in results between textdescriptives and [textstat](https://pypi.org/project/textstat/) for German language, especially for Gunning Fog and Flesch Reading Ease, but other metrics too. I also noticed differences for English texts.

- Why is that? 
- And according to your experience: Which metrics are reliable in textdescriptives for German (or more broadly other European languages that aren't English)?

By the way: Thanks very much for making textdescriptives available! This is very helpful and very much appreciated. 👍

## How to reproduce the behaviour
```
import spacy
import textstat
import textdescriptives as td
from tabulate import tabulate

def get_metrics(text):
    """Get text metrics from textstat and textdescriptives."""

    results = []
    results.append(textstat.flesch_reading_ease(text))
    results.append(textstat.flesch_kincaid_grade(text))
    results.append(textstat.smog_index(text))
    results.append(textstat.gunning_fog(text))
    results.append(textstat.automated_readability_index(text))
    results.append(textstat.coleman_liau_index(text))
    results.append(textstat.char_count(text))
    results.append(textstat.lexicon_count(text, removepunct=False))
    results.append(textstat.sentence_count(text))
    results.append(textstat.avg_sentence_length(text))
    txst = pd.DataFrame(
        results,
        index=[
            "flesch_reading_ease",
            "flesch_kincaid_grade",
            "smog",
            "gunning_fog",
            "automated_readability_index",
            "coleman_liau_index",
            "char_count",
            "lexicon_count",
            "sentence_count",
            "avg_sentence_length",
        ],
        columns=["textstat"],
    ).reset_index(names=["txst"])

    doc = nlp(text)
    tmp01 = pd.DataFrame.from_dict(
        doc._.readability, orient="index", columns=["textdescriptives"]
    )
    tmp02 = pd.DataFrame.from_dict(
        doc._.descriptive_stats, orient="index", columns=["textdescriptives"]
    )
    txsc = pd.concat([tmp01, tmp02], axis=0)
    idx = [
        "flesch_reading_ease",
        "flesch_kincaid_grade",
        "smog",
        "gunning_fog",
        "automated_readability_index",
        "coleman_liau_index",
        "n_characters",
        "n_tokens",
        "n_sentences",
        "sentence_length_mean",
    ]
    txsc = txsc.loc[idx].reset_index(names=["metrics"])
    df = pd.concat([txsc, txst], axis=1).drop("txst", axis=1)
    df["diff %"] = 100 - (df["textdescriptives"] / df["textstat"] * 100)
    return df

textstat.set_lang("de")
nlp = spacy.load("de_core_news_lg")
nlp.add_pipe("textdescriptives/readability")
text = """Ich gehe heute zur Schule. \
Ich will pünktlich in die Klasse kommen. \
Meine Uhr zeigt acht Uhr mitteleuropäischer Zeitrechnung. """

# textstat.set_lang("en")
# nlp = spacy.load("en_core_web_lg")
# nlp.add_pipe("textdescriptives/readability")
# text = """I'm going to school today. \
# I want to get to class on time. \
# My watch shows eight o'clock Central European Time."""

text = text * 10
print(
    tabulate(
        get_metrics(text),
        headers="keys",
        floatfmt=".2f",
        tablefmt="github",
        showindex=False,
    )
)

```
Output

```
| metrics                     |   textdescriptives |   textstat |   diff % |
|-----------------------------|--------------------|------------|----------|
| flesch_reading_ease         |              49.02 |      68.40 |    28.34 |
| flesch_kincaid_grade        |               8.00 |       8.10 |     1.29 |
| smog                        |               7.79 |       7.80 |     0.08 |
| gunning_fog                 |               6.74 |       2.94 |  -129.38 |
| automated_readability_index |               7.52 |       8.30 |     9.43 |
| coleman_liau_index          |              11.71 |      11.19 |    -4.66 |
| n_characters                |            1070.00 |    1070.00 |     0.00 |
| n_tokens                    |             190.00 |     190.00 |     0.00 |
| n_sentences                 |              30.00 |      30.00 |     0.00 |
| sentence_length_mean        |               6.33 |       6.30 |    -0.53 |
```

## Your Environment

* textdescriptives Version Used: 2.6.2
* Operating System: MacOS 13.5
* Python Version Used: 3.9.16

**Comment by KennethEnevoldsen** [comment]
Removing the *bug* label as it isn't clear that it is a bug.

Thanks posting this issue. Our formulas for calculations are available [here](https://hlasse.github.io/TextDescriptives/readability.html) and implementation generally follow those of the package `spacy-readability`. However, do note that all of these metrics relies on estimated properties for instance determining average sentence length for `flesch_reading_ease` requires detection of sentence boundaries (using a different underlying model in textdescriptives will yield different results in edge cases, but generally it is fairly robust). This also seems like it is support by the fact that the mean sentence length is not a perfect match. The difference however seems to big... (in cases of disagreement it seems like spacy is typically better than textstat)

Actually it seems like textstat uses a different constant for Fleiss reading ease than our implementation (probably the main cause). The source is unclear but googling seems to stem from a [German Thesis](https://www.worldcat.org/title/wie-verstandlich-sind-unsere-zeitungen/oclc/32497323). So we assume a language agnostic constant (which is fitted on English) It might be better to use a language specific constant instead. Hmm there might also be a better default constant than the English one. (@HLasse, @LudvigOlsen  what are your thoughts?). Seems like the syllables threshold for what constitutes hard words. textstat seems to use a default of 2 for German, where we use 3 (same as English), which is probably too low for German. It should probably be higher due to compound word.

**Comment by HLasse** [comment]
Actually, IIRC, we based our implementation off of `textstat` so the values should be fairly similar (except for the differences in sentence detection etc., that you bring up, Kenneth). 

+1 for Kenneth's comment: the minor deviations are most likely due to different sentence boundary detection and tokenization methods and are fairly negligible and tend to even out with longer texts. 

Re. flesch reading ease, the implementations and constants are completely similar between [textdescriptives](https://github.com/HLasse/TextDescriptives/blob/9594a268c725614aa87a05c7b32073211d6f9eef/src/textdescriptives/components/readability.py#L26C8-L26C9) and [textstat](https://github.com/textstat/textstat/blob/0ed2dda9d1f68abbdf4109861fa18f7fa043930c/textstat/textstat.py#L679) for the English language. My initial suspicion was that we use different modules for hyphenation (counting syllables), but both use `pyphen`. So, there is likely to be a bug or at least an implementation difference in the way syllables are counted between the two libraries ([textstat implementation](https://github.com/textstat/textstat/blob/0ed2dda9d1f68abbdf4109861fa18f7fa043930c/textstat/textstat.py#L412), [textdescriptives implementation](https://github.com/HLasse/TextDescriptives/blob/9594a268c725614aa87a05c7b32073211d6f9eef/src/textdescriptives/components/utils.py#L29). We should definitely look into this.

Re. gunning fog: This boils down to what Kenneth says: `textstat` uses a different threshold for hard words for German (2 syllables) than for English (3 syllables), where we use the threshold of 3 syllables regardless of language.

Re. your last point on the reliability of metrics for languages besides English: We have sought to implement metrics that are broadly reliable across all languages. What we mean by this, is that the rank-ordering of texts in terms of any of the metrics will correctly order them by reading ease. However, some metrics ( Flesch-Kincaid Grade) have constants that have been derived through modelling English text. The grade level will therefore likely only be reliable for English, but the metric is still useful for other languages for ranking the difficulty of texts (and is likely not that far off). 

I'll look into the hyphenation implementations in 2-3 weeks' time unless someone beats me to it. 

Hope this answers your question, @rnckp!
